AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test Step Functions and Lambda locally

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: Deployment environment (e.g., dev, staging, prod)

Resources:
  StepFunctionLambda1:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: handler.lambda_handler
      CodeUri: ./src/StepFunctionLambda1
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  StepFunctionLambda2:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: handler.lambda_handler
      CodeUri: ./src/StepFunctionLambda2
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  StepFunctionLambda3:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: handler.lambda_handler
      CodeUri: ./src/StepFunctionLambda3
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment

  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: 'api.yaml'

  RestApiRole:
      Type: 'AWS::IAM::Role'
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                - apigateway.amazonaws.com
              Action:
                - 'sts:AssumeRole'
        Policies:
        - PolicyName: AllowSFNExec
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "states:StartExecution"
                Resource: !GetAtt MyStateMachine.Arn

  StepFunctionExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - states.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: StepFunctionLambdaInvoke
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource:
                    - !GetAtt StepFunctionLambda1.Arn
                    - !GetAtt StepFunctionLambda2.Arn
                    - !GetAtt StepFunctionLambda3.Arn
  
  MyStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine-asl.json
      Role: !GetAtt StepFunctionExecutionRole.Arn
      DefinitionSubstitutions:
        Lambda1Arn: !GetAtt StepFunctionLambda1.Arn
        Lambda2Arn: !GetAtt StepFunctionLambda2.Arn
        Lambda3Arn: !GetAtt StepFunctionLambda3.Arn

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL to call Hello World State Machine"
    Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
  HelloWorldStateMachineArn:
    Description: "Hello World State Machine ARN"
    Value: !Ref MyStateMachine
  HelloWorldStateMachineRole:
    Description: "IAM Role created for Hello World State Machine based on the specified SAM Policy Templates"
    Value: !GetAtt StepFunctionExecutionRole.Arn
